[package]
name = "binance2ledger-cli"
version = "0.1.0"
authors = ["ihsan <ihsanl@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
binance = { git = "https://github.com/wisespace-io/binance-rs.git" }

